### ISSUE TITLE
Invoke debot implementation

### ISSUE THREAD

**Issue by MaxAkkerman** [extraton/debrowser#2]
Will be very nice if you can implement invoke functionality in you debot browser

**Comment by qwertys318** [comment]
Hello. What is "invoke functionality"?

**Comment by MaxAkkerman** [comment]
**run debot**
---**tonos-cli debot fetch 0:fca49c6cf57f1654988f944f2e9874cb3c86a33dabbc7c3948326fb912dedefa**
Config: default
Connecting to https://net.ton.dev
DeBot Info:
Name   : RT Voting Audit System 1.0
Version: 0.1.0
Author : Radiance Team
Publisher: Radiance Team
Support: 0:841288ed3b55d9cdafa806807f02a0ae0c169aa5edfe88a789a6482429756a94
Description: DeBot for DeAudit by Radiance Team
That's debot for Voting Audit. Developed by Radiance Team
Run the DeBot (y/n)?
y

Welcome to Radiance Voting Audit debot interface.
1) Voting audits
2) Login
3) Sign up
4) Quit

**choose Login and enter seed phrase below**
debash$ 2
Enter your seed phrase:
**task equal dash medal disagree mule artefact waste glory road problem matter**
Checked success
Your address: 0:4193ebaae4c7f78b4064de884bd59f83e0e1185eb1e88809f414857bd5349dfc
 Balance:
 5205520942 nanoTONs
Main Menu:
1) Action team
2) Collator
3) Validator
4) return to main menu
5) Quit

**Here choose Action Team - it will invoke(process) another debot. This what i mean invoke func.**
debash$ 1
DeBot Info:
Name   : Radiance Voting Audit DeBot [Action Team]
Version: 0.1.0
Author : Radiance Team
Publisher: Radiance Team
Support: 0:841288ed3b55d9cdafa806807f02a0ae0c169aa5edfe88a789a6482429756a94
Description: DeBot for Action Team of Voting Audit Debots by Radiance Team.
Please note that this is part of the Radiance Voting Audit debots. Use Core Voting Audit Debot for easy navigation
Run the DeBot (y/n)?
y
Welcome to Action team menu
1) Refresh data
2) Create DeAudit Data
3) Edit DeAudit Data
4) Add member to Action Team
5) Remove member from Action Team
6) Force Finish DeAudit
7) Initiate DeAudit
8) Display Votings
9) Return to main menu
10) Quit

**Addreses and seed phareses**
For net.ton.dev
tonos-cli debot fetch 0:fca49c6cf57f1654988f944f2e9874cb3c86a33dabbc7c3948326fb912dedefa
client seed phrase:
task equal dash medal disagree mule artefact waste glory road problem matter

For fld.ton.dev
tonos-cli --url https://gql.custler.net debot fetch 0:cf1dfd0b87492bb30bbbd70db84665ee3c383465e7c297df23704bcd9ddb9fd6
client seed phrase:
foster rapid layer frozen mirror brick what chuckle garden first peasant flee

And would be nice if you can add fld.ton.dev network because of net.ton.dev unstable last time

**Comment by qwertys318** [comment]
Understand, thank you. Okay, we will implement this.

> And would be nice if you can add fld.ton.dev network because of net.ton.dev unstable last time

You can call debots from any networks by following address schema:
`[server/]address`
So, to call your debot from fld network just input:
`gql.custler.net/0:cf1dfd0b87492bb30bbbd70db84665ee3c383465e7c297df23704bcd9ddb9fd6`

**Comment by qwertys318** [comment]
tag 1.4.5
check it, please
