### ISSUE TITLE
Add ability to change keys 

### ISSUE THREAD

**Issue by MaxAkkerman** [extraton/debrowser#3]
Please add the ability to change keys for on-chain requests.

<img width="987" alt="Снимок экрана 2021-08-11 в 15 15 25" src="https://user-images.githubusercontent.com/55087980/129031204-5c910720-cc93-4122-9dfa-d6ea3dd64fd1.png">

**Comment by qwertys318** [comment]
We added checkbox "Save for this session" on keys request.
1.6.0
