### ISSUE TITLE
DeBot icon

### ISSUE THREAD

**Issue by mikekaban0v** [extraton/debrowser#5]
The debot icon doesn't show in the browser (shows as a broken image).
![image](https://user-images.githubusercontent.com/75077775/130470827-7da3637c-dbc1-423a-99ae-152f27a9778f.png)

**Comment by qwertys318** [comment]
please, provide debot address

**Comment by mikekaban0v** [comment]
0:a7115bb9984210697943d409c7bbc77e1db6e2021bb38cb2ebc88d7fdfdf528c

![image](https://user-images.githubusercontent.com/75077775/132809045-81f21f84-6965-4193-bbab-3a5b3e69809e.png)

**Comment by qwertys318** [comment]
Fixed in 1.6.0
